# Use docker-based infrastructure
sudo: false

language: java

jdk:
  - oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories:
    - "$HOME/.m2/repository"

install: /bin/true

script:
  - mvn -q -U -T 2 -Pjavadoc,compatibility,snapshots install jacoco:report
  - mvn -q coveralls:report -DrepoToken=$COVERALLS_TOKEN
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then mvn -q -DskipTests=true -Pjavadoc deploy; fi
