#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

basePackages: some.other.pkg
logs: WARN
jndi:
  additionalContexts:
    test1: /jndi-test1.properties
    test2: /jndi-test2.properties
application: seed-it
secret1: "**I am ${person${index1}}**"
person1: Alice
index1: 1
someEnum: FOO
someShorts: [ 2, 3, 4 ]
anInt: 5
empty:
